
name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build
        run: echo "Build success"

  test:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Test
        run: echo "Tests passed"

  deploy:
    runs-on: self-hosted
    needs: [build, test]
    steps:
      - name: Deploy using WSL
        run: |
          wsl chmod +x /mnt/c/Users/HP/Cloud-free-CI-CD/Cloud-free-CI-CD/deploy.sh
          wsl bash /mnt/c/Users/HP/Cloud-free-CI-CD/Cloud-free-CI-CD/deploy.sh
